---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeromq-test
  labels:
    app: zeromq-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: zeromq-test
  template:
    metadata:
      name: zeromq-test
      labels:
        app: zeromq-test
    spec:
      containers:
        - name: zeromq
          image: lukas8219/zeromq_poc
          ports:
          - containerPort: 3000
          env:
          - name: PUB_HOST_ADDRESS
            value: "127.0.0.1"
          - name: SUB_HOST_ADDRESS
            value: "zeromq-test"
          - name: PUB_PORT
            value: "3000"
          - name: SUB_PORT
            value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: zeromq-test
  labels:
    app: zeromq-test
spec:
  type: ClusterIP
  selector:
    app: zeromq-test
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zeromq-test
spec:
  hosts:
  - zeromq-test
  tcp:
  - match:
    - port: 3000
    route:
    - destination:
        host: zeromq-test.default.svc.cluster.local
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: zeromq-test
spec:
  host: zeromq-test
  trafficPolicy:
    loadBalancer:
      simple: PASSTHROUGH